"""Initial Migration

Revision ID: b6d702ee9541
Revises: b5c22589ff92
Create Date: 2018-07-02 20:13:04.067288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d702ee9541'
down_revision = 'b5c22589ff92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('content', sa.String(), nullable=True))
    op.drop_column('pitches', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'content')
    # ### end Alembic commands ###
